import type {GetStatisProps} from "next";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import WorkExperience from "../components/WorkExperience";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import ContactMe from "../components/ContactMe";
import Link from 'next/link';
import {Experience, PageInformation, Project, Skill, Social} from "../typings";
import {fetchSocials} from "../utils/fetchSocials"
import {fetchSkills} from "../utils/fetchSkills";
import {fetchProjects} from "../utils/fetchProjects";
import {fetchExperiences} from "../utils/fetchExperiences";
import {fetchPageInformation} from "../utils/fetchPageInformation";


type Props = {
  pageInformation: PageInformation;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
}
const Home = ({projects, skills, socials, pageInformation, experiences}: Props) => {
  return (
    
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory 
    overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]">
      <Head>
        <title>Yudong's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header socials = {socials}/>

     {/* Hero*/}
    <section id="hero" className="snap-start">
        <Hero pageInformation={pageInformation}/>
      </section>

    {/* About*/}
    <section id="about" className="snap-center">
      <About pageInformation={pageInformation}/>
    </section>

    {/*Experience*/}
    <section id="experience" className="snap-center">
      <WorkExperience experiences={experiences}/>
    </section>

    {/*Skills*/}
    <section id="skills" className="snap-start">
      <Skills skills={skills}/>
    </section>

    {/*Projects*/}
    <section id="projects" className="snap-start">
      <Projects  projects={projects}/>
    </section>

    {/*Contact Me*/}
    <section id="contactme" className="snap-start">
    <ContactMe />
    </section>

    <Link href="#hero">
      <footer className="sticky bottom-5 w-full cursor-pointer">
        <div className="flex items-center justify-evenly">
          <img
          className="h-10 w-10 rounded-full filter grayscale hover:grascale-0
          cursor-pointer"
          src="https://i.imgur.com/e2yvD6A.png"

          />
        </div>
      </footer>
    </Link>
    
    </div>
  )
}

export default Home;

export const getStaticProps: GetStatisProps<Props> = async () => {
  const socials: Social[] = await fetchSocials();
  const pageInformation: PageInformation = await fetchPageInformation();
  const experiences: Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  

  return {
    props: {
      pageInformation,
      experiences,
      skills,
      projects,
      socials,
    },

    revalidate: 15,
  }
}
